site_name: Home Assistant Docs
nav:
  - Home: index.md
  - Configuration: configuration.md
  - Home Guide Per Room: area-guide.md
  - Integrations: integrations.md
  - Devices: devices.md
  - Complete Device Catalog: device-catalog.md
  - Automations: automations.md
  - Skills: skills.md
theme:
  name: material

extra:
  repository: ../
