site_name: Home Assistant Docs
nav:
  - Home: index.md
  - Home Guide Per Room: area-guide.md
  - Automations: automations.md
  - Scene & Button Actions: scripts.md
theme:
  name: material

extra:
  repository: ../
